### ISSUE TITLE
WoLFPSORT site does not exist any more

### ISSUE THREAD

**Issue by jmfernandez** [psipred/FFPred#1]
Following the installation instructions at FFPred_README I have found that WoLFPSORT dependency is not available at its original site any more.

Luckily, I have found a copy of it in github, at https://github.com/fmaguire/WoLFPSort , so you could update FFPred_README, pointing to it.

**Comment by DanBuchan** [comment]
Ah yes. We had come across this but the change had not made its way to the readme file

As psort is something of abandonware there is no guarantee that some arbitrary git repo will be maintained. For now our solution is to distribute our own copy of the psort zip file for as long as we are distributing FFPRed source code.
